apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvhost-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pvhost-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "pvhost-helm.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "pvhost-helm.fullname" . }}
        {{- include "pvhost-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: pvhost-metrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "/data"
          volumeMounts:
            - mountPath: /data
              name: data-volume
          ports:
            - name: metrics
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pv.claimName | default (printf "%s-claim" (include "pvhost-helm.fullname" .)) }}