apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.claimName | default (printf "%s-claim" (include "pvhost-helm.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    volumeType: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.storageCapacity }}
  volumeName: {{ .Values.pv.claimName | default (include "pvhost-helm.fullname" .) }}-volume