apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.claimName | default (include "pvhost-helm.fullname" .) }}-volume
  namespace: {{ .Release.Namespace }}
  annotations:
    pv.beta.kubernetes.io/gid: {{.Values.pv.gid}}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pv.storageCapacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.pv.hostPath }}
